# Generated by Django 5.0.2 on 2025-07-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstableentry',
            name='nrr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pointstableentry',
            name='overs_against',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pointstableentry',
            name='overs_for',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pointstableentry',
            name='runs_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointstableentry',
            name='runs_for',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
