# Generated by Django 5.0.2 on 2025-07-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_pointstableentry_nrr_pointstableentry_overs_against_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='overs_per_innings',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pom_matches', to='teams.player'),
        ),
        migrations.CreateModel(
            name='PlayerMatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('overs_bowled', models.FloatField(default=0.0)),
                ('wickets_taken', models.PositiveIntegerField(default=0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('economy_rate', models.FloatField(default=0.0)),
                ('catches_taken', models.PositiveIntegerField(default=0)),
                ('stumpings', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_performances', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_performances', to='teams.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TournamentAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('player_of_tournament', 'Player of the Tournament'), ('highest_run_scorer', 'Highest Run Scorer'), ('highest_wicket_taker', 'Highest Wicket Taker'), ('best_batsman', 'Best Batsman'), ('best_bowler', 'Best Bowler'), ('best_all_rounder', 'Best All-Rounder')], max_length=30)),
                ('value', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_awards', to='teams.player')),
            ],
            options={
                'unique_together': {('award_type',)},
            },
        ),
    ]
