# Generated by Django 5.0.2 on 2025-07-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_overs_per_innings_match_player_of_match_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermatchperformance',
            options={'verbose_name': 'Player Match Performance 🏏', 'verbose_name_plural': 'Player Match Performances 🏏'},
        ),
        migrations.AlterModelOptions(
            name='tournamentawards',
            options={'verbose_name': 'Tournament Award 🏆', 'verbose_name_plural': 'Tournament Awards 🏆'},
        ),
    ]
