# Generated by Django 5.0.2 on 2025-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_playermatchperformance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermatchperformance',
            options={'verbose_name': 'Player Match Performance', 'verbose_name_plural': 'Player Match Performances'},
        ),
        migrations.AlterModelOptions(
            name='tournamentawards',
            options={'verbose_name': 'Tournament Award', 'verbose_name_plural': 'Tournament Awards'},
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(),
        ),
    ]
