"""
Django settings for ipl_tournament project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!=t34baal@fjyfqvr=w=l^d#2fo^c^xpe2_*&dkz&jzbk#)my1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mini-tournament-3.onrender.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'teams',
    'matches',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ipl_tournament.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ipl_tournament.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "🏏 GPL Mini Tournament",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "🏏 Gali Premier League",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "🏏 GPL Tournament",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": None,

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "🏏 Welcome to Gali Premier League Mini Tournament",

    # Copyright on the footer
    "copyright": "🏏 Gali Premier League Mini Tournament Ltd",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    "search_model": ["teams.Team", "teams.Player", "matches.Match"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [

        {"name": "🏠 Dashboard",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "🏏 Tournament", "url": "/", "new_window": True},
        {"name": "📊 Statistics", "url": "/matches/statistics/", "new_window": True},
        {"name": "🏆 Awards", "url": "/matches/awards/", "new_window": True},
        {"app": "teams"},
        {"app": "matches"},
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "teams.Team": "fas fa-flag",
        "teams.Player": "fas fa-user-friends",
        "matches.Match": "fas fa-gamepad",
        "matches.PointsTableEntry": "fas fa-trophy",
        "matches.PlayerMatchPerformance": "fas fa-chart-line",
        "matches.TournamentAwards": "fas fa-medal",
    },

    # Custom icons for side menu apps/models when collapsed
    "icons_collapsed": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "teams.Team": "fas fa-flag",
        "teams.Player": "fas fa-user-friends",
        "matches.Match": "fas fa-gamepad",
        "matches.PointsTableEntry": "fas fa-trophy",
        "matches.PlayerMatchPerformance": "fas fa-chart-line",
        "matches.TournamentAwards": "fas fa-medal",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": True,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "teams.Team": "horizontal_tabs",
        "teams.Player": "horizontal_tabs",
        "matches.Match": "horizontal_tabs",
        "matches.PointsTableEntry": "horizontal_tabs",
    },
    # Add a language dropdown into the admin
    "language_chooser": False,
    
    ###############
    # Responsive #
    ###############
    # Make admin responsive
    "responsive": True,
    
    # Custom CSS for beautiful admin dashboard
    "custom_css": """
    <style>
    /* Beautiful Admin Dashboard Styles */
    
    /* Gradient Background */
    body {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
        min-height: 100vh;
    }
    
    /* Main Content Area */
    .content-wrapper {
        background: rgba(255, 255, 255, 0.95) !important;
        backdrop-filter: blur(10px);
        border-radius: 15px;
        margin: 20px;
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
    }
    
    /* Header Styling */
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
        border-bottom: none !important;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
    }
    
    .navbar-brand {
        font-weight: 700 !important;
        font-size: 1.5rem !important;
        color: white !important;
        text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
    }
    
    /* Sidebar Styling */
    .main-sidebar {
        background: linear-gradient(180deg, #2c3e50 0%, #34495e 100%) !important;
        box-shadow: 4px 0 20px rgba(0, 0, 0, 0.1);
    }
    
    .sidebar-dark-primary .nav-sidebar > .nav-item > .nav-link {
        color: #ecf0f1 !important;
        border-radius: 10px;
        margin: 2px 10px;
        transition: all 0.3s ease;
    }
    
    .sidebar-dark-primary .nav-sidebar > .nav-item > .nav-link:hover {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
        transform: translateX(5px);
        box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
    }
    
    .sidebar-dark-primary .nav-sidebar > .nav-item > .nav-link.active {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
        box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
    }
    
    /* Dashboard Cards */
    .dashboard-card {
        background: white;
        border-radius: 15px;
        padding: 25px;
        margin-bottom: 20px;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease;
        border: none;
    }
    
    .dashboard-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.15);
    }
    
    .stat-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 15px;
        padding: 25px;
        margin-bottom: 20px;
        box-shadow: 0 10px 30px rgba(102, 126, 234, 0.3);
        transition: all 0.3s ease;
    }
    
    .stat-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 20px 40px rgba(102, 126, 234, 0.4);
    }
    
    .stat-card h3 {
        font-size: 2.5rem;
        font-weight: 700;
        margin: 0;
        text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
    }
    
    .stat-card p {
        font-size: 1.1rem;
        margin: 10px 0 0 0;
        opacity: 0.9;
    }
    
    /* Different colored stat cards */
    .stat-card.primary {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }
    
    .stat-card.success {
        background: linear-gradient(135deg, #56ab2f 0%, #a8e6cf 100%);
    }
    
    .stat-card.warning {
        background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
    }
    
    .stat-card.info {
        background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
    }
    
    .stat-card.dark {
        background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);
    }
    
    /* Table Styling */
    .table {
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    }
    
    .table thead th {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border: none;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    
    .table tbody tr:hover {
        background: rgba(102, 126, 234, 0.1);
        transform: scale(1.01);
        transition: all 0.3s ease;
    }
    
    /* Button Styling */
    .btn {
        border-radius: 25px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
        transition: all 0.3s ease;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
    }
    
    .btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);
    }
    
    .btn-primary {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border: none;
    }
    
    .btn-success {
        background: linear-gradient(135deg, #56ab2f 0%, #a8e6cf 100%);
        border: none;
    }
    
    .btn-warning {
        background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        border: none;
    }
    
    .btn-info {
        background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        border: none;
    }
    
    /* Form Styling */
    .form-control {
        border-radius: 10px;
        border: 2px solid #e9ecef;
        transition: all 0.3s ease;
    }
    
    .form-control:focus {
        border-color: #667eea;
        box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);
    }
    
    /* Card Styling */
    .card {
        border-radius: 15px;
        border: none;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease;
    }
    
    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.15);
    }
    
    .card-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 15px 15px 0 0 !important;
        border: none;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    
    /* Alert Styling */
    .alert {
        border-radius: 10px;
        border: none;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    }
    
    /* Progress Bar */
    .progress {
        border-radius: 25px;
        height: 10px;
        background: rgba(102, 126, 234, 0.1);
    }
    
    .progress-bar {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 25px;
    }
    
    /* Mobile responsive styles */
    @media (max-width: 768px) {
        .navbar-brand {
            font-size: 1.2rem !important;
        }
        
        .sidebar {
            width: 100% !important;
            position: fixed !important;
            z-index: 9999 !important;
        }
        
        .main-header {
            padding: 0.5rem !important;
        }
        
        .content-header {
            padding: 0.5rem !important;
        }
        
        .content {
            margin-left: 0 !important;
            padding: 0.5rem !important;
        }
        
        .table-responsive {
            overflow-x: auto !important;
        }
        
        .btn {
            padding: 0.375rem 0.75rem !important;
            font-size: 0.875rem !important;
        }
        
        .form-control {
            font-size: 0.875rem !important;
        }
        
        .card {
            margin-bottom: 1rem !important;
        }
        
        .card-body {
            padding: 1rem !important;
        }
        
        .modal-dialog {
            margin: 0.5rem !important;
            max-width: calc(100% - 1rem) !important;
        }
        
        .modal-body {
            padding: 1rem !important;
        }
        
        .dropdown-menu {
            position: static !important;
            float: none !important;
            width: 100% !important;
            margin-top: 0.5rem !important;
        }
        
        .navbar-nav .dropdown-menu {
            position: static !important;
            float: none !important;
            width: 100% !important;
            margin-top: 0.5rem !important;
        }
        
        .sidebar-mini .main-sidebar {
            transform: translateX(-100%) !important;
        }
        
        .sidebar-mini.sidebar-collapse .main-sidebar {
            transform: translateX(0) !important;
        }
    }
    
    /* Tablet responsive styles */
    @media (min-width: 769px) and (max-width: 1024px) {
        .content {
            margin-left: 250px !important;
        }
        
        .sidebar {
            width: 250px !important;
        }
        
        .main-header {
            margin-left: 250px !important;
        }
    }
    
    /* Touch-friendly elements */
    .btn, .form-control, .dropdown-toggle {
        min-height: 44px !important;
    }
    
    .table th, .table td {
        padding: 0.75rem !important;
    }
    
    /* Better mobile navigation */
    .sidebar-mini .main-sidebar {
        transition: transform 0.3s ease-in-out !important;
    }
    
    /* Mobile menu toggle */
    .sidebar-toggle {
        display: block !important;
    }
    
    @media (min-width: 769px) {
        .sidebar-toggle {
            display: none !important;
        }
    }
    
    /* Animation for dashboard elements */
    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translateY(30px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }
    
    .dashboard-card, .stat-card {
        animation: fadeInUp 0.6s ease-out;
    }
    
    /* Custom scrollbar */
    ::-webkit-scrollbar {
        width: 8px;
    }
    
    ::-webkit-scrollbar-track {
        background: #f1f1f1;
        border-radius: 10px;
    }
    
    ::-webkit-scrollbar-thumb {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 10px;
    }
    
    ::-webkit-scrollbar-thumb:hover {
        background: linear-gradient(135deg, #5a6fd8 0%, #6a4190 100%);
    }
    </style>
    """,
    
    # Custom JavaScript for beautiful admin dashboard
    "custom_js": """
    <script>
    // Beautiful Admin Dashboard Functionality
    document.addEventListener('DOMContentLoaded', function() {
        // Handle mobile sidebar toggle
        const sidebarToggle = document.querySelector('.sidebar-toggle');
        const body = document.body;
        
        if (sidebarToggle) {
            sidebarToggle.addEventListener('click', function(e) {
                e.preventDefault();
                body.classList.toggle('sidebar-collapse');
            });
        }
        
        // Auto-hide sidebar on mobile when clicking outside
        document.addEventListener('click', function(e) {
            if (window.innerWidth <= 768) {
                const sidebar = document.querySelector('.main-sidebar');
                const toggle = document.querySelector('.sidebar-toggle');
                
                if (sidebar && !sidebar.contains(e.target) && !toggle.contains(e.target)) {
                    body.classList.remove('sidebar-collapse');
                }
            }
        });
        
        // Handle window resize
        window.addEventListener('resize', function() {
            if (window.innerWidth > 768) {
                body.classList.remove('sidebar-collapse');
            }
        });
        
        // Make tables responsive
        const tables = document.querySelectorAll('.table');
        tables.forEach(function(table) {
            if (!table.parentElement.classList.contains('table-responsive')) {
                const wrapper = document.createElement('div');
                wrapper.className = 'table-responsive';
                table.parentNode.insertBefore(wrapper, table);
                wrapper.appendChild(table);
            }
        });
        
        // Improve form responsiveness
        const forms = document.querySelectorAll('form');
        forms.forEach(function(form) {
            form.classList.add('needs-validation');
        });
        
        // Add smooth scrolling
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            });
        });
        
        // Add loading animations
        const cards = document.querySelectorAll('.dashboard-card, .stat-card');
        cards.forEach((card, index) => {
            card.style.animationDelay = (index * 0.1) + 's';
        });
        
        // Add hover effects for interactive elements
        const interactiveElements = document.querySelectorAll('.btn, .card, .table tbody tr');
        interactiveElements.forEach(element => {
            element.addEventListener('mouseenter', function() {
                this.style.transition = 'all 0.3s ease';
            });
        });
    });
    </script>
    """,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
